[[questions]]
question = "When is the global clustering not a good representation of the network? Tell me the reason."
answer = "When the network is degree heterogeneous. This is because a single hub can create substantially many triangles in the network, not representing the number of triangles typical nodes in the network form."

[[questions]]
question = "When is the average path length not a good representation of the network? Tell me the reason."
answer = "When the network is degree heterogeneous. If hubs are present, they can substantially reduce the average path lengths via hub nodes. "